# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-21 05:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('user_type', models.CharField(choices=[('f', 'facebook'), ('g', 'google'), ('d', 'django')], default='d', max_length=1)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='이메일 주소')),
                ('nickname', models.CharField(max_length=30, unique=True, verbose_name='닉네임')),
                ('is_active', models.BooleanField(default=True, verbose_name='활성화')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='가입 날짜')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '사용자',
                'verbose_name_plural': '사용자 목록',
                'ordering': ('-date_joined',),
            },
        ),
    ]
