# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 07:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20171124_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nickname',
            field=models.CharField(max_length=255, unique=True, verbose_name='닉네임'),
        ),
    ]
