# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-25 08:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20171125_1654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='social_id',
            field=models.CharField(blank=True, max_length=255, verbose_name='소셜 아이디'),
        ),
    ]
