# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 10:23
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_auto_20171212_1854'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.3', editable=False, max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.3', editable=False, max_length=20),
        ),
    ]
