# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-28 07:51
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20171128_1630'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetBreeds',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('breeds_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='pet',
            name='species',
        ),
        migrations.RemoveField(
            model_name='petspecies',
            name='name',
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='petbreeds',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.PetSpecies'),
        ),
        migrations.AddField(
            model_name='pet',
            name='breeds',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='account.PetBreeds'),
        ),
    ]
