# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_auto_20171130_2033'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='PetBreeds',
            new_name='PetBreed',
        ),
        migrations.AlterModelOptions(
            name='petspecies',
            options={'verbose_name_plural': 'PetSpecies'},
        ),
    ]
