# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 13:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20171130_2210'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='petspecies',
            options={},
        ),
    ]
