# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0013_auto_20171130_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is_active'),
        ),
    ]
