# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0014_pet_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(),
        ),
    ]
