# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-04 09:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0015_auto_20171204_1801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='is_neutering',
            field=models.BooleanField(default=False),
        ),
    ]
