# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 07:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0018_auto_20171206_1155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='breeds',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.PetBreed'),
        ),
        migrations.AlterField(
            model_name='pet',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.PetSpecies'),
        ),
    ]
