# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-09 11:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0020_auto_20171209_1955'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pet',
            options={'ordering': ('-pk',)},
        ),
    ]
