# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-12 11:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0021_auto_20171209_2021'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='device_token',
            field=models.CharField(blank=True, max_length=160, verbose_name='device_token'),
        ),
    ]
