# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 05:32
from __future__ import unicode_literals

from django.db import migrations, models
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0022_user_device_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='pet',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', null=True, upload_to='Pets', width_field='width'),
        ),
        migrations.AddField(
            model_name='pet',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='pet',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='height',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(height_field='height', null=True, upload_to='Users', width_field='width'),
        ),
        migrations.AddField(
            model_name='user',
            name='ppoi',
            field=versatileimagefield.fields.PPOIField(default='0.5x0.5', editable=False, max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='width',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
