# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 05:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20171213_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='ppoi',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='width',
        ),
    ]
