# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 07:46
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0023_auto_20171213_1432'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pet',
            old_name='ppoi',
            new_name='thumbnail_ppoi',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='ppoi',
            new_name='thumbnail_ppoi',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='height',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='width',
        ),
        migrations.RemoveField(
            model_name='user',
            name='height',
        ),
        migrations.RemoveField(
            model_name='user',
            name='width',
        ),
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Pets', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Users', verbose_name='thumbnail'),
        ),
    ]
