# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-13 11:43
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0024_auto_20171213_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, upload_to='Users', verbose_name='thumbnail'),
        ),
    ]
