# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 07:32
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0031_auto_20171214_1622'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, default='settings.STATIC_DIR/placeholder/placeholder_human.png', null=True, upload_to='Users', verbose_name='thumbnail'),
        ),
    ]
