# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-14 10:04
from __future__ import unicode_literals

from django.db import migrations
import versatileimagefield.fields


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0033_auto_20171214_1730'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Pets', verbose_name='thumbnail'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=versatileimagefield.fields.VersatileImageField(blank=True, null=True, upload_to='Users', verbose_name='thumbnail'),
        ),
    ]
