# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 07:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0034_auto_20171214_1904'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pet',
            name='image',
        ),
        migrations.RemoveField(
            model_name='pet',
            name='thumbnail_ppoi',
        ),
        migrations.RemoveField(
            model_name='user',
            name='image',
        ),
        migrations.RemoveField(
            model_name='user',
            name='thumbnail_ppoi',
        ),
    ]
