# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0037_pet_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='file',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
