# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 10:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0038_user_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='file',
        ),
    ]
