# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 15:20
from __future__ import unicode_literals

from django.db import migrations
import utils.custom_image_field


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0039_remove_user_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='image',
            field=utils.custom_image_field.CustomImageField(blank=True, upload_to='thumbnail/pet'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=utils.custom_image_field.CustomImageField(blank=True, max_length=255, upload_to='thumbnail/user'),
        ),
    ]
