# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-21 13:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import medical.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BodySize',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goal_weight', models.FloatField(blank=True, null=True)),
                ('current_weight', models.FloatField(blank=True, null=True)),
                ('chest', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('neck', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Inoculation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_of_times', models.PositiveSmallIntegerField(default=1)),
                ('inoculated_date', models.DateTimeField(blank=True, null=True)),
                ('hospital', models.CharField(blank=True, max_length=100)),
                ('is_alarm', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=medical.models.user_directory_path)),
                ('date', models.DateField(blank=True, null=True)),
                ('description', models.CharField(max_length=70)),
                ('comment', models.TextField(blank=True, max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='PetMedical',
            fields=[
                ('pet', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pet_set', serialize=False, to='account.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Vaccine',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('turn', models.PositiveSmallIntegerField(default=1)),
                ('period', models.DurationField(default=datetime.timedelta(28))),
                ('inoculations', models.ManyToManyField(through='medical.Inoculation', to='medical.PetMedical')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_set', to='account.PetSpecies')),
            ],
        ),
        migrations.AddField(
            model_name='operation',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_set', to='medical.PetMedical'),
        ),
        migrations.AddField(
            model_name='inoculation',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inoculation_set', to='medical.PetMedical'),
        ),
        migrations.AddField(
            model_name='inoculation',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_set', to='medical.Vaccine'),
        ),
        migrations.AddField(
            model_name='bodysize',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='body_size_set', to='medical.PetMedical'),
        ),
    ]
