# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-18 12:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vaccineinoculation',
            name='num_of_times',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
