# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-15 04:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PetOperation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=None)),
                ('date', models.DateField()),
                ('description', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True, max_length=500)),
                ('pet_operation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_operations', to='medical.PetMedical')),
            ],
        ),
        migrations.RemoveField(
            model_name='operation',
            name='operations',
        ),
        migrations.AlterField(
            model_name='petsize',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size', to='medical.PetMedical'),
        ),
        migrations.AlterField(
            model_name='vaccineinfo',
            name='vaccine_info',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.PetSpecies'),
        ),
        migrations.DeleteModel(
            name='Operation',
        ),
    ]
