# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-20 12:14
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsize',
            old_name='weight',
            new_name='current_weight',
        ),
        migrations.AddField(
            model_name='petsize',
            name='goal_weight',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='petmedical',
            name='pet',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='pet_set', serialize=False, to='account.Pet'),
        ),
        migrations.AlterField(
            model_name='petoperation',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operation_set', to='medical.PetMedical'),
        ),
        migrations.AlterField(
            model_name='petsize',
            name='medical',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_size_set', to='medical.PetMedical'),
        ),
        migrations.AlterField(
            model_name='vaccine',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species_set', to='account.PetSpecies'),
        ),
        migrations.AlterField(
            model_name='vaccineinoculation',
            name='vaccine',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vaccine_set', to='medical.Vaccine'),
        ),
    ]
