# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 06:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0003_auto_20171219_1529'),
    ]

    operations = [
        migrations.RenameField(
            model_name='petsize',
            old_name='create_date',
            new_name='created_date',
        ),
    ]
