# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-19 07:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('medical', '0004_auto_20171219_1556'),
    ]

    operations = [
        migrations.AlterField(
            model_name='petsize',
            name='created_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
